[package]
name = "blake2-ffi-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
lean-ffi = { git = "https://github.com/argumentcomputer/lean-ffi", rev = "2ee6267354ce460a8dd95ae9f087cc2569a90ad6" }
revm-precompile = { version = "32.1.0", default-features = false, features = ["std"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
